### ISSUE TITLE
Crashing due to getMacAddress is not a function

### ISSUE THREAD

**Issue by xiao99xiao** [tasict/homebridge-daikin-local-platform#6]
The plugin has been running for months but suddenly today it keeps crashing due to the the error below:

```
[6/17/2024, 10:27:36 AM] [Daikin Local Platform] Restoring accessory 'ワークスペース' (5026EFAE30CC) from cache.
[6/17/2024, 10:27:36 AM] TypeError: cachedAccessory.context.device.getMacAddress is not a function
    at DaikinPlatform.checkDevices (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/platform.ts:131:53)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DaikinPlatform.configurePlugin (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/platform.ts:72:5)
[6/17/2024, 10:31:07 AM] Got SIGTERM, shutting down Homebridge...
```

Tried reverting to 1.0.10 but the crash still continues.

System: macOS 12.7.5 on Intel Mac mini
Nodejs: v20.14.0

**Comment by xiao99xiao** [comment]
Resolved by removing all plugin cache.
