### ISSUE TITLE
Frequent crash occurring

### ISSUE THREAD

**Issue by jadonbaker** [tasict/homebridge-daikin-local-platform#7]
I'm getting this crash occur which will cause home bridge or the child bridge to terminate and restart.

`homebridge-daikin-local-platform v1.1.1`
`Node.js Version	v20.17.0`

```
`[20/09/2024, 10:56:03] [Daikin Local Platform] Restoring accessory 'Bedroom' (D810689551F8) from cache.
[20/09/2024, 10:56:24] [Homebridge UI] Terminal session ended.

/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/AxiosError.js:92
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: read ECONNRESET
    at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:519:28)
    at ClientRequest.eventHandlers.<computed> (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/node_modules/follow-redirects/index.js:39:24)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at Socket.socketErrorListener (node:_http_client:511:5)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DaikinDevice.queryDevice (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/daikin-local.ts:60:22)
    at DaikinDevice.fetchDeviceStatus (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/daikin-local.ts:87:22)
    at ClimateAccessory.refreshDeviceStatus (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/accessories/climate.ts:155:5)
[20/09/2024, 10:57:28] [Daikin Local Platform] Child bridge process ended
[20/09/2024, 10:57:28] [Daikin Local Platform] Process Ended. Code: 1, Signal: null`
```

**Comment by jadonbaker** [comment]
Looks like it's an issue with node v20.17.0
Have not noticed it occur on v18.20.4

Edit: actually it is occurring on 18.20.4

**Comment by jadonbaker** [comment]
Please can you update the plugin to catch this AxiosError when thrown to prevent the child bridge from crashing.

**Comment by chrisremie** [comment]
I have the same issue

**Comment by tasict** [comment]
@jadonbaker @chrisremie  Done. Please update new version.

**Comment by chrisremie** [comment]
After the update I now get this:

[10/04/2025, 14:53:23] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (node:internal/crypto/hash:115:11)
    at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at /var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/platform.ts:86:40
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DaikinPlatform.checkDevices (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/platform.ts:83:5)
    at DaikinPlatform.configurePlugin (/var/lib/homebridge/node_modules/homebridge-daikin-local-platform/src/platform.ts:72:5)

**Comment by tasict** [comment]
@chrisremie please try new verison.

**Comment by chrisremie** [comment]
Now I get this:
[12/04/2025, 12:06:25] [Daikin Local Platform] Device undefined has no MAC address - skipping.

**Comment by tasict** [comment]
[Daikin Local Platform] Device undefined has no MAC address - skipping.
is expected in this case. Previously, the plugin would crash if the device didn't respond with a MAC address. Now, it simply skips over the device and logs this warning instead, as a safeguard.

Could you please double-check if the IP address you've configured is correct and still valid for the Daikin unit?

**Comment by chrisremie** [comment]
I have this in JSON config:
{
            "name": "Daikin Local Platform",
            "climateIPs": [
                "192.168.188.160"
            ],
            "debugMode": true,
            "platform": "Daikin Local Platform"
        }

And my modem confirms this IP address is the airco and returns a MAC address

**Comment by tasict** [comment]
I refine the code and avoid error data when airco connection is unstable.

**Comment by chrisremie** [comment]
Now this:
[13/04/2025, 16:57:42] [Daikin Local Platform] Daikin - fetchDeviceStatus(false): Error: No response from device
