### ISSUE TITLE
Error: connect EHOSTUNREACH <ip>

### ISSUE THREAD

**Issue by ycliuntu** [tasict/homebridge-daikin-local-platform#8]
There is an error below. My firmware version is 2.8.0, and the AC can be controlled by the app Daikin Mobile Controller.

/usr/local/lib/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/AxiosError.js:92
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: connect EHOSTUNREACH 192.168.1.102:80 - Local (192.168.1.111:60958)
    at Function.AxiosError.from (/usr/local/lib/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/homebridge-daikin-local-platform/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:513:28)
    at emitErrorEvent (node:_http_client:104:11)
    at Socket.socketErrorListener (node:_http_client:512:5)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at Axios.request (/usr/local/lib/node_modules/homebridge-daikin-local-platform/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at DaikinDevice.queryDevice (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/daikin-local.ts:60:22)
    at DaikinDevice.fetchDeviceStatus (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/daikin-local.ts:87:22)
    at DaikinLocalAPI.fetchDevices (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/daikin-local.ts:627:10)
    at DaikinPlatform.checkDevices (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/platform.ts:83:5)
    at DaikinPlatform.configurePlugin (/usr/local/lib/node_modules/homebridge-daikin-local-platform/src/platform.ts:72:5)
[12/5/2024, 11:48:37 PM] [Daikin Local Platform] Child bridge process ended
[12/5/2024, 11:48:37 PM] [Daikin Local Platform] Process Ended. Code: 1, Signal: null

**Comment by ycliuntu** [comment]
I think it is related to the Local Network setting in MacOs 15
